### ISSUE TITLE
pdm - ModuleNotFoundError: No module named 'editables'

### ISSUE THREAD

**Issue by InLaw** [nix-community/dream2nix#1030]
nix develop
```
Traceback (most recent call last):
  File "/nix/store/1s273zzc3jrzyci3iznq9bcjcz8s821z-editable.py", line 239, in <module>
    make_editable(
  File "/nix/store/1s273zzc3jrzyci3iznq9bcjcz8s821z-editable.py", line 65, in make_editable
    editable_dist_info = make_dist_info(
                         ^^^^^^^^^^^^^^^
  File "/nix/store/1s273zzc3jrzyci3iznq9bcjcz8s821z-editable.py", line 112, in make_dist_info
    dist_info_name = backend.prepare_metadata_for_build_editable(tmp_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dgngk6nyflj70f38g9kx44g8c6yzyia0-python3-3.11.9-env/lib/python3.11/site-packages/pdm/backend/__init__.py", line 87, in prepare_metadata_for_build_editable
    from pdm.backend.editable import EditableBuilder
  File "/nix/store/dgngk6nyflj70f38g9kx44g8c6yzyia0-python3-3.11.9-env/lib/python3.11/site-packages/pdm/backend/editable.py", line 7, in <module>
    from editables import EditableProject
ModuleNotFoundError: No module named 'editables'
```

**Comment by purepani** [comment]
I believe this was fixed in a recent-ish nixpkgs update
 Could you try running `nix flake update`?

**Comment by InLaw** [comment]
already did it, now again
- no changes

**Comment by purepani** [comment]
If you need a temporary fix, putting `config.deps.python.pkgs.editables` in `mkDerivation.nativeBuildInputs` will fix it. Could you share a minimally reproducable repo(or even just a reproducable one).

**Comment by InLaw** [comment]
thanks 
- works if in `buildInputs`

**Comment by InLaw** [comment]
`flake.nix`
```
{
  description = "dream2nix - m";

  inputs = {
    dream2nix.url = "github:nix-community/dream2nix";
    nixpkgs.follows = "dream2nix/nixpkgs";
  };

  outputs = inputs @ {
    self,
    dream2nix,
    nixpkgs,
    #devShells,
    ...
  }: let
    system = "x86_64-linux";
  in {
    packages.${system}.default = dream2nix.lib.evalModules {
      packageSets.nixpkgs = inputs.dream2nix.inputs.nixpkgs.legacyPackages.${system};
      modules = [
        ./default.nix 
        {
          paths.projectRoot = ./.;
          paths.projectRootFile = "flake.nix";
          paths.package = ./.;
        }
      ];
    };

    devShell.${system} = self.packages.${system}.default.devShell;   
  };
}
```

`default.nix`
```
{
  config,
  dream2nix,
  lib,
  ...

}: 
let
  deps = config.deps;
  stdenv = deps.stdenv;
#in let 
  dream2nixSource =
    builtins.fetchTarball {
      url = "https://github.com/nix-community/dream2nix/tarball/main";
    }
    ;
  pkgs = import (import dream2nixSource {}).inputs.nixpkgs {} ;
in 
{
  imports = [
    dream2nix.modules.dream2nix.WIP-python-pdm
  ];

  deps = {nixpkgs, ...}: {
    inherit 
      (nixpkgs) 
      xdotool 
      spyder
      vscode
      neofetch
      bash ;

    python = nixpkgs.python311Full; 
  };

  pdm.lockfile = ./pdm.lock;
  pdm.pyproject = ./pyproject.toml;
  
  mkDerivation = rec {
    src = ./.;

    nativeBuildInputs = [ 
      ]
       ++ [ 
    ]  
      ;

    buildInputs = [
     config.deps.python.pkgs.editables 

      config.deps.python.pkgs.pdm-backend 
    ]
    ++ [ 
      config.deps.neofetch
    ]  
    ;

    propagatedBuildInputs = [ 
      config.deps.neofetch # not working
      ];

    shellHook = ''
      LANG="en_US.UTF-8"
    '';

    postFixup = ''
        echo "PostFix"   
      '';
    

  };
} 
```

**Comment by purepani** [comment]
I can't quite seem to reproduce this at all(copying your code, and removing the editables package, and using a test `pyproject.toml` with the pdm backend. Perhaps there was a weird garbage-collection issue going on? Could you try removing the editables package and removing `./.dream2nix` in the root directory?

**Comment by InLaw** [comment]
What does it mean to remove `./.dream2nix`

**Comment by purepani** [comment]
To make editables work, there is a folder in the root of the project called `.dream2nix` that is generated. I'm just asking what happens if you remove that folder and try running `nix develop` again so that it gets regenerated.

**Comment by InLaw** [comment]
I cannot find that folder
![202407-30_10:35:56](https://github.com/user-attachments/assets/9b1f5f7f-f7cb-4785-a337-9899de69d169)
