### ISSUE TITLE
sveltekit: no devShell

### ISSUE THREAD

**Issue by bbigras** [nix-community/dream2nix#272]
```sh
nix shell "nixpkgs#nodejs"

# skeleton project, "no" to everything
npm create svelte@latest svelte-dream2nix

cd svelte-dream2nix

mv .gitignore .gitignore.bak

nix flake init -t github:nix-community/dream2nix#simple

git init
git add .

nix eval --impure --raw --expr 'builtins.currentSystem' > ./nix_systems && git add ./nix_systems

❯ nix develop
warning: Git tree '/home/bbigras/dev/svelte-dream2nix' is dirty
error: flake 'git+file:///home/bbigras/dev/svelte-dream2nix' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'

❯ nix flake show
warning: Git tree '/home/bbigras/dev/svelte-dream2nix' is dirty
git+file:///home/bbigras/dev/svelte-dream2nix
├───packages
│   └───x86_64-linux
│       ├───resolveImpure: package 'resolve'
│       └───svelte-dream2nix: package 'svelte-dream2nix'
└───projectsJson: unknown
```

**Comment by bezmuth** [comment]
When attempting to `nix build .#svelte-dream2nix` you should get this error:
```bash
error: The nodejs package svelte-dream2nix contains unresolved impurities.
       Resolve by running the .resolve attribute of this derivation
       or by resolving all impure projects by running the `resolveImpure` package
```
You can fix this by running:
```bash
nix build .#resolveImpure

./result/bin/resolve
```
Then you should be able to run `nix develop`

**Comment by bbigras** [comment]
Thanks, it works. Now I get:

```
[bbigras@laptop:~/dev/svelte-dream2nix]$ npm run dev

> svelte-dream2nix@0.0.1 dev /home/bbigras/dev/svelte-dream2nix
> vite dev

failed to load config from /home/bbigras/dev/svelte-dream2nix/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /home/bbigras/dev/svelte-dream2nix/node_modules/@sveltejs/kit/src/exports/node/polyfills.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
```

**Comment by DavHau** [comment]
We should probably also generate a fake `devShell` alongside the fake package, allowing us to raise an error if it is evaluated hinting about `resolveImpure`

**Comment by bezmuth** [comment]
I'll try implementing this
