### ISSUE TITLE
NodeJS translator: missing dependency

### ISSUE THREAD

**Issue by fufexan** [nix-community/dream2nix#289]
Me and @a-kenji were trying to package [Misskey](https://github.com/misskey-dev/misskey) using dream2nix [here](https://github.com/fufexan/misskey-d2n).

<details>
<summary>
The error we got:
</summary>

```
packages__slash__client-unknown> building
packages__slash__client-unknown> > @ build /nix/store/jc3sjifirk4vi6p29sr3pqf63nwww9z5-packages__slash__client-unknown/lib/node_modules/packages/client
packages__slash__client-unknown> > vite build
packages__slash__client-unknown> ✘ [ERROR] Could not resolve "../../locales"
packages__slash__client-unknown>     vite.config.ts:5:20:
packages__slash__client-unknown>       5 │ import locales from '../../locales';
packages__slash__client-unknown>         ╵                     ~~~~~~~~~~~~~~~
packages__slash__client-unknown> ✘ [ERROR] Could not resolve "../../package.json"
packages__slash__client-unknown>     vite.config.ts:6:17:
packages__slash__client-unknown>       6 │ import meta from '../../package.json';
packages__slash__client-unknown>         ╵                  ~~~~~~~~~~~~~~~~~~~~
packages__slash__client-unknown> failed to load config from /nix/store/jc3sjifirk4vi6p29sr3pqf63nwww9z5-packages__slash__client-unknown/lib/node_modules/packages/client/vite.config.ts
packages__slash__client-unknown> error during build:
packages__slash__client-unknown> Error: Build failed with 2 errors:
packages__slash__client-unknown> vite.config.ts:5:20: ERROR: Could not resolve "../../locales"
packages__slash__client-unknown> vite.config.ts:6:17: ERROR: Could not resolve "../../package.json"
packages__slash__client-unknown>     at failureErrorWithLog (/nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:1605:15)
packages__slash__client-unknown>     at /nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:1251:28
packages__slash__client-unknown>     at runOnEndCallbacks (/nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:1034:63)
packages__slash__client-unknown>     at buildResponseToResult (/nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:1249:7)
packages__slash__client-unknown>     at /nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:1358:14
packages__slash__client-unknown>     at /nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:666:9
packages__slash__client-unknown>     at handleIncomingPacket (/nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:763:9)
packages__slash__client-unknown>     at Socket.readFromStdout (/nix/store/lqxk5wx7d0mq8na5awch9zny8wb6kny2-esbuild-0.14.48/lib/node_modules/esbuild/lib/main.js:632:7)
packages__slash__client-unknown>     at Socket.emit (events.js:400:28)
packages__slash__client-unknown>     at addChunk (internal/streams/readable.js:293:12)
packages__slash__client-unknown> npm ERR! code ELIFECYCLE
packages__slash__client-unknown> npm ERR! errno 1
packages__slash__client-unknown> npm ERR! @ build: `vite build`
packages__slash__client-unknown> npm ERR! Exit status 1
packages__slash__client-unknown> npm ERR!
packages__slash__client-unknown> npm ERR! Failed at the @ build script.
packages__slash__client-unknown> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
packages__slash__client-unknown>
packages__slash__client-unknown> npm ERR! A complete log of this run can be found in:
packages__slash__client-unknown> npm ERR!     /build/.npm/_logs/2022-09-05T10_11_11_430Z-debug.log
```

</details>

It seems that the `os-locale` dependency can't be found. We tried both the `package-lock` and the `yarn-lock` translators, and we also tried overriding the source with the appropriate package injection https://github.com/fufexan/misskey-d2n/tree/overrides. It looks like dream2nix doesn't try to fetch the injected package that we set.

**Comment by yusdacra** [comment]
I can build the `misskey` package fine on the branch you linked. It doesn't seem to produce anything that I can run though, so I'm not sure if it actually works or not. I just did `nix build .#misskey` and then put in the missing hash for `os-locale`, then it built fine.

**Comment by yusdacra** [comment]
I think that build error might be pointing to something else? It tries to build `/nix/store/fbdjs66j36cdckljcwqvdkwdgd9y590g-packages__slash__client-unknown/lib/node_modules/packages/client`, but then tries to access `../../package.json` but that relative path does not exist, because where `../..` points to only has a `packages` directory. So it looks like it's trying to access the top-level `package.json` of misskey, but can't because it doesn't exist (same with `locales`). Maybe you could try putting those files where it expects them to be, but not sure if that would work and even if it would it sounds like a hacky solution. Maybe dream2nix should just build these using the same source, the full misskey repo itself, instead of separating the sources for the packages. For example this is what the Rust builders do if the source is a Cargo workspace. Maybe nodejs has something similar, or at least the user should be able to specify something for this.

**Comment by DavHau** [comment]
Yeah several people already ran into that kind of problem. We should make source isolation optional, so sub-packages can access each others source.

**Comment by fufexan** [comment]
Has there been any progress on this? Any way I can help?

**Comment by DavHau** [comment]
@fufexan I created #307 with some more description on what needs to be done here. Feel free to reply on that issue if something is not clear, or you need help in some way.
