### ISSUE TITLE
nuxt 3 project fails building

### ISSUE THREAD

**Issue by Suyashtnt** [nix-community/dream2nix#310]
building a nuxt 3 project via dream2nix does not work due to the way nuxi handles project roots.
relevant log:
```
> 37-ocean-breeze@ build /nix/store/dlyxmpnjga0wa0n3bh4c862j7vaxrga4-37-ocean-breeze-unknown/lib/node_modules/37-ocean-breeze
> nuxt build

Nuxi 3.0.0-rc.11
Nuxt 3.0.0-rc.11 with Nitro 0.5.4

 ERROR  Cannot detect workspace root from /nix/store/dlyxmpnjga0wa0n3bh4c862j7vaxrga4-37-ocean-breeze-unknown/lib/node_modules/37-ocean-breeze

  at findWorkspaceDir (node_modules/pkg-types/dist/index.mjs:117:9)
  at async loadOptions (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2271:26)
  at async createNitro (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2347:19)
  at async initNitro (node_modules/nuxt/dist/index.mjs:1402:17)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1612:3)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1635:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:732:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 37-ocean-breeze@ build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 37-ocean-breeze@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2022-09-29T11_24_55_449Z-debug.log
```

relevant part as screenshot
![image](https://user-images.githubusercontent.com/45307955/193019791-a69fc912-75aa-4d50-8f20-dc2df597ee0e.png)

**Comment by Suyashtnt** [comment]
hmm, after some testing, it seems to be only happening when using direnv, running `nix develop` works fine

**Comment by han-um** [comment]
in my case, update npm fixed it 

`npm install -g npm@latest`

it seems to be an issue with the npm version.
I didn't have this issue when using pnpm.

**Comment by DavHau** [comment]
I was not able to reproduce this issue on a freshly initialized nuxt3 project. Could you provide a flake that reproduces the issue?
