### ISSUE TITLE
/examples/python_pip

### ISSUE THREAD

**Issue by InLaw** [nix-community/dream2nix#464]
setup:
```
 - system: `"x86_64-linux"` 
 - host os: `Linux 5.15.88, NixOS, 22.11 (Raccoon), 22.11.1705.b83e7f5a04a` 
 - multi-user?: `yes` 
 - sandbox: `yes` 
 - version: `nix-env (Nix) 2.11.1` 
 - channels(root): `"nixos-22.11, nixos-hardware"` 
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

--

https://github.com/nix-community/dream2nix/tree/main/examples/python_pip

following 
https://nix-community.github.io/dream2nix/guides/getting-started-python.html

examples/python_pip$ nix build .#default
error: flake 'path:/home//python_pip' does not provide attribute 'packages.x86_64-linux.default', 'legacyPackages.x86_64-linux.default' or 'default'

results in 
`examples/python_pip$ nix build .#default`
`error: flake 'path:/home//python_pip' does not provide attribute 'packages.x86_64-linux.default', 'legacyPackages.x86_64-linux.default' or 'default'`

**Comment by phaer** [comment]
`'path:/home//python_pip'` this doesn't look like the right path. The `.` in `.#` represents the current directory, so what does `pwd` output for you? Is your copy of the example part of a git repo? What does `nix flake show` say, do you see the packages there?

**Comment by InLaw** [comment]
yes, it is the example from the repo 
analogous like in https://github.com/nix-community/dream2nix/issues/429

currently 
```
cd python_pip/
direnv: loading ~/../examples/python_pip/.envrc
direnv: using flake
[1/0/1 copied (32.0/123.4 MiB), 5.8/20.9 MiB DL] fetching source from https://cache.nixos.orgdirenv: ([/nix/store/nrj92sd5xv0lym6x6z1ih0ndnlb7wc37-direnv-2.32.1/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
```
takes > 3 min to load ?!

nix flake show
```
path:/home/../examples/python_pip?lastModified=1675173658&narHash=sha256-ndBXMuP%2fjFC68GhXtiMSMrJHXnSmZCpXFADKNW8wqzU=
├───apps
│   └───x86_64-linux
│       └───detect-projects: app
├───checks
│   └───x86_64-linux
│       ├───aiohttp: derivation 'aiohttp'
│       └───resolveImpure: derivation 'resolve'
└───packages
    └───x86_64-linux
        ├───aiohttp: package 'aiohttp'
        └───resolveImpure: package 'resolve'
```

**Comment by phaer** [comment]
Its about the absolute path, e.g.

> loading ~/../examples/python_pip/.envrc

Whats that path? Do you really have a /home/examples directory?  For comparison, executing the same command in a checkout of dream2nix main branch in `~/src/dream2nix` results in the following for me:

```
dream2nix/examples/python_pip on  main [$!+] via ❄️  impure (dream2nix-devshell) 
❯ nix flake show
git+file:///home/phaer/src/dream2nix?dir=examples%2fpython_pip
├───apps
│   └───x86_64-linux
│       └───detect-projects: app
├───checks
│   └───x86_64-linux
│       ├───aiohttp: derivation 'python3.8-aiohttp'
│       ├───default: derivation 'python3.8-aiohttp'
│       └───resolveImpure: derivation 'resolve'
├───devShells
│   └───x86_64-linux
│       └───aiohttp: development environment 'nix-shell'
└───packages
    └───x86_64-linux
        ├───aiohttp: package 'python3.8-aiohttp'
        ├───default: package 'python3.8-aiohttp'
        └───resolveImpure: package 'resolve'
```

**Comment by InLaw** [comment]
dream2nix/examples/python_pip]$ nix flake show
```
warning: creating lock file '/home/dream2nix/examples/python_pip/flake.lock'
warning: Git tree '/home/dream2nix' is dirty
git+file:///home/dream2nix?dir=examples%2fpython_pip
├───apps
│   └───x86_64-linux
│       └───detect-projects: app
├───checks
│   └───x86_64-linux
│       ├───aiohttp: derivation 'aiohttp'
│       └───resolveImpure: derivation 'resolve'
└───packages
    └───x86_64-linux
        ├───aiohttp: package 'aiohttp'
        └───resolveImpure: package 'resolve'

```

which is your nixos/nix version?

**Comment by phaer** [comment]
dream2nix commit is current main or `28da5efffd1a8ead08cf0bb13047a51f351b9ce6`.
NixOS 22.11, nix 2.11.0.

**Comment by InLaw** [comment]
nix develop 
```
warning: Git tree '/home/dream2nix' is dirty
error: flake 'git+file:///home/dream2nix?dir=examples%2fpython_pip' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

nix build .#default
`error: flake 'git+file:///home/dream2nix?dir=examples%2fpython_pip' does not provide attribute 'packages.x86_64-linux.default', 'legacyPackages.x86_64-linux.default' or 'default'`



what else could make those differences?

**Comment by phaer** [comment]
Have you confirmed that you are on a clean checkout of the latest commit of the dream2nix main branch? i.e.
```
git pull origin main
git branch
git status
```

**Comment by InLaw** [comment]
there error continues (like it is)
---
`Your branch is up to date with 'origin/main'.`

nix flake show
```
warning: Git tree '/home/dream2nix' is dirty
git+file:///home/dream2nix
├───apps
│   ├───aarch64-darwin
│   │   ├───detect-projects: app
│   │   ├───docs: app
│   │   ├───format: app
│   │   ├───index: app
│   │   ├───install: app
│   │   ├───runNixCmdInSrc: app
│   │   ├───tests-all: app
│   │   ├───tests-examples: app
│   │   ├───tests-integration: app
│   │   ├───tests-integration-d2n-flakes: app
│   │   ├───tests-unit: app
│   │   ├───translate: app
│   │   └───translate-index: app
│   ├───aarch64-linux
│   │   ├───detect-projects: app
│   │   ├───docs: app
│   │   ├───format: app
│   │   ├───index: app
│   │   ├───install: app
│   │   ├───runNixCmdInSrc: app
│   │   ├───tests-all: app
│   │   ├───tests-examples: app
│   │   ├───tests-integration: app
│   │   ├───tests-integration-d2n-flakes: app
│   │   ├───tests-unit: app
│   │   ├───translate: app
│   │   └───translate-index: app
│   ├───x86_64-darwin
│   │   ├───detect-projects: app
│   │   ├───docs: app
│   │   ├───format: app
│   │   ├───index: app
│   │   ├───install: app
│   │   ├───runNixCmdInSrc: app
│   │   ├───tests-all: app
│   │   ├───tests-examples: app
│   │   ├───tests-integration: app
│   │   ├───tests-integration-d2n-flakes: app
│   │   ├───tests-unit: app
│   │   ├───translate: app
│   │   └───translate-index: app
│   └───x86_64-linux
│       ├───detect-projects: app
│       ├───docs: app
│       ├───format: app
│       ├───index: app
│       ├───install: app
│       ├───runNixCmdInSrc: app
│       ├───tests-all: app
│       ├───tests-examples: app
│       ├───tests-integration: app
│       ├───tests-integration-d2n-flakes: app
│       ├───tests-unit: app
│       ├───translate: app
│       └───translate-index: app
├───checks
│   ├───aarch64-darwin
│   │   └───pre-commit-check: derivation 'pre-commit-run'
│   ├───aarch64-linux
│   │   └───pre-commit-check: derivation 'pre-commit-run'
│   ├───x86_64-darwin
│   │   └───pre-commit-check: derivation 'pre-commit-run'
│   └───x86_64-linux
│       └───pre-commit-check: derivation 'pre-commit-run'
├───darwinModules: unknown
├───devShells
│   ├───aarch64-darwin
│   │   ├───default: development environment 'dream2nix-devshell'
│   │   └───dream2nix-shell: development environment 'dream2nix-devshell'
│   ├───aarch64-linux
│   │   ├───default: development environment 'dream2nix-devshell'
│   │   └───dream2nix-shell: development environment 'dream2nix-devshell'
│   ├───x86_64-darwin
│   │   ├───default: development environment 'dream2nix-devshell'
│   │   └───dream2nix-shell: development environment 'dream2nix-devshell'
│   └───x86_64-linux
│       ├───default: development environment 'dream2nix-devshell'
│       └───dream2nix-shell: development environment 'dream2nix-devshell'
├───flakeModuleBeta: unknown
├───formatter
├───legacyPackages
│   ├───aarch64-darwin omitted (use '--legacy' to show)
│   ├───aarch64-linux omitted (use '--legacy' to show)
│   ├───x86_64-darwin omitted (use '--legacy' to show)
│   └───x86_64-linux omitted (use '--legacy' to show)
├───lib: unknown
├───lib2: unknown
├───nixosConfigurations
├───nixosModules
├───overlays
├───packages
│   ├───aarch64-darwin
│   │   └───docs: package 'dream2nix-docs'
│   ├───aarch64-linux
│   │   └───docs: package 'dream2nix-docs'
│   ├───x86_64-darwin
│   │   └───docs: package 'dream2nix-docs'
│   └───x86_64-linux
│       └───docs: package 'dream2nix-docs'
└───templates
    ├───_d2n-auto-project-detection: template: Example: _d2n-auto-project-detection template
    ├───_d2n-define-projects-manually: template: Example: _d2n-define-projects-manually template
    ├───_d2n-extend-devShell: template: Example: _d2n-extend-devShell template
    ├───_d2n-extended: template: Example: _d2n-extended template
    ├───_d2n-extended-new-subsystem: template: Example: _d2n-extended-new-subsystem template
    ├───_d2n-flake-parts: template: Example: _d2n-flake-parts template
    ├───_d2n-indexer: template: Example: _d2n-indexer template
    ├───_d2n-init-pkgs: template: Example: _d2n-init-pkgs template
    ├───_d2n-projects-as-attrs: template: Example: _d2n-projects-as-attrs template
    ├───debian-binary: template: Example: debian-binary template
    ├───default: template: Simple dream2nix flake
    ├───haskell_cabal: template: Example: haskell_cabal template
    ├───haskell_cabal-freeze: template: Example: haskell_cabal-freeze template
    ├───haskell_cabal-plan: template: Example: haskell_cabal-plan template
    ├───haskell_stack-lock: template: Example: haskell_stack-lock template
    ├───nodejs_alternative_builder: template: Example: nodejs_alternative_builder template
    ├───nodejs_eslint: template: Example: nodejs_eslint template
    ├───nodejs_eslint-aggreagted: template: Example: nodejs_eslint-aggreagted template
    ├───nodejs_prettier: template: Example: nodejs_prettier template
    ├───nodejs_workspace: template: Example: nodejs_workspace template
    ├───php_composer: template: Example: php_composer template
    ├───python_pip: template: Example: python_pip template
    ├───python_pip-freeze: template: Example: python_pip-freeze template
    ├───python_poetry: template: Example: python_poetry template
    ├───racket: template: Example: racket template
    ├───rust_no-cargo-lock: template: Example: rust_no-cargo-lock template
    ├───rust_ripgrep: template: Example: rust_ripgrep template
    ├───rust_set-rust-toolchain: template: Example: rust_set-rust-toolchain template
    └───simple: template: Simple dream2nix flake

```

nix flake show
```
warning: Git tree '/home/dream2nix' is dirty
git+file:///home/dream2nix?dir=examples%2fpython_pip
├───apps
│   └───x86_64-linux
│       └───detect-projects: app
├───checks
│   └───x86_64-linux
│       ├───aiohttp: derivation 'aiohttp'
│       └───resolveImpure: derivation 'resolve'
└───packages
    └───x86_64-linux
        ├───aiohttp: package 'aiohttp'
        └───resolveImpure: package 'resolve'

```

nix build .#default
```
warning: Git tree '/home/dream2nix' is dirty
error: flake 'git+file:///home/dream2nix?dir=examples%2fpython_pip' does not provide attribute 'packages.x86_64-linux.default', 'legacyPackages.x86_64-linux.default' or 'default'
```

**Comment by phaer** [comment]
I am sorry, turns out **I** wasn't on the latest release, due to a stray lockfile.

Default output seems to have been removed, we'll need to update the docs. Meanwhile, building the example should work with the following commands:

```
nix run .#resolveImpure  # or nix run .#aiohttp.resolve for a single package
nix build .#aiohttp 
```

**Comment by InLaw** [comment]
nix build .#main
- fails -  as before  `does not provide attribute 'packages.x86_64-linux.main', 'legacyPackages.x86_64-linux.main' or 'main'`
(so `nix build . `works without errors )

nix run .#resolveImpure  
- makes a build

but 
`python `
```
Python 3.8.14 (default, Sep  6 2022, 21:10:26) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import aiohttp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by phaer** [comment]
> nix build .#main
> 
>     * fails -  as before  `does not provide attribute 'packages.x86_64-linux.main', 'legacyPackages.x86_64-linux.main' or 'main'`
>       (so `nix build . `works without errors )

Yes, because there's no project named main in the python pip example, but there is one in the docs. That's why i wrote the concrete example for python_pip in my comment above, try .#aiohttp - as that's the project defined in python_pips project.toml.

> 
> nix run .#resolveImpure
> 
>     * makes a build

That alone should only write the lock file, not make a build.

> but `python `
> 
> ```
> Python 3.8.14 (default, Sep  6 2022, 21:10:26) 
> [GCC 11.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> >>> import aiohttp
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'aiohttp'
> ```

The expected result is a `./results` symlink to your built python package, not a python env with your package in PYTHON_PATH..

> 
> fails again with `does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'` if not python "3.8" is used

What fails here exactly? Your post does not contain a command above that paragraph.

**Comment by InLaw** [comment]
not python "3.8" is used, it fails again with `does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'`
> 
> What fails here exactly? Your post does not contain a command above that paragraph.


nix build . 
```
warning: Git tree '/home/dream2nix' is dirty
error: flake 'git+file:///home/dream2nix?dir=examples%2fpython_pip' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

nix develop . 
```
warning: Git tree '/home/dream2nix' is dirty
error: flake 'git+file:///home/dream2nix?dir=examples%2fpython_pip' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

**Comment by nhooey** [comment]
@InLaw: Could you mention in the issue description that this workaround fixes the issue, so others can find it?

**Workaround:**
```bash
nix run .#resolveImpure
nix build .#default
```
