### ISSUE TITLE
strict-builder for nodejs fails on package; 'File exists' when _create_package_from_derivation tries to create symlinks

### ISSUE THREAD

**Issue by irisjae** [nix-community/dream2nix#471]
The package 'react-native-unimodules' builds successfully with the granular builder, but fails on the strict builder. Here's a minimal reproduction of the issue https://github.com/irisjae/dream2nix-test-case

Nix logs gives us the following stack trace:
```
Traceback (most recent call last):
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/bin/.d2nNodeModules-wrapped", line 9, in <module>
    sys.exit(d2nNodeModules())
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/main.py", line 34, in d2nNodeModules
    create_node_modules()
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 133, in create_node_modules
    _make_folders_rec(
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 105, in _make_folders_rec
    _create_package_from_derivation(
  File "/nix/store/2q2h7x71jzj3kcddkpcqkn62q39f6fgz-builder/lib/python3.10/site-packages/app/lib/node_modules.py", line 54, in _create_package_from_derivation
    (target / Path(entry)).symlink_to(dep.derivation / Path(entry))
  File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: '/nix/store/2gliinpkw8mjwlmjv5vnqxxp2yvr0vll-__at__babel__slash__core-7.9.0-lib/node_modules' -> '/nix/store/5k03wg3dlawpng2r5c4pg290pmhddarv-node-modules/@babel/core/node_modules'
```

I'm not sure why such a scenario of symlinking to a path that already exists is possible from a brief look at the Python builder script.

**Comment by DavHau** [comment]
@hsjobeki

**Comment by hsjobeki** [comment]
@irisjae thank you for the Issue and the example. Well done. I encountered that issue once in a very large project and didn't yet figure out why it happens. I have a fix for it ready but i want to find the "root cause" of that problem. So your example project is very nice, because it is small. I'll create a fix for it asap these days.
