### ISSUE TITLE
Wheel version doesn't exist after doing..something?

### ISSUE THREAD

**Issue by purepani** [nix-community/dream2nix#683]
I was playing around with dream2nix and python packaging, and I did something to my laptop that seemed to cause any attempt to use dream2nix pip to fail due to it not being able to find a wheel version 0.40.0. I am able to get it working on other systems, so it is something that happened to my setup, giving the following error each time I try and create the lock file for a python package
`ERROR: Could not find a version that satisfies the requirement wheel==0.40.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0a0, 0.30.0, 0.31.0, 0.31.1, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.33.4, 0.33.5, 0.33.6, 0.34.0, 0.34.1, 0.34.2, 0.35.0, 0.35.1, 0.36.0, 0.36.1, 0.36.2, 0.37.0, 0.37.1, 0.38.0, 0.38.1, 0.38.2, 0.38.3, 0.38.4)
ERROR: No matching distribution found for wheel==0.40.0
`

I don't know what I should be doing to completely reset whatever cached information that dream2nix may have downloaded, so it would be good if I could be directed in that direction. I appreciate any help.

I am also completely unsure what could have caused this, so it might be a bug, since I was only trying to get dream2nix working. The only thing I was doing when this started happening was generating lock files repeatedly.

**Comment by purepani** [comment]
I should add:
The repo i tested this with is this:
https://github.com/purepani/dream2nix_test

It uses the flake example and 2 of the python examples from the examples folder directly.

**Comment by purepani** [comment]
Here's the full error:
```
warning: Git tree '/home/satwik/projects/testdream2nix' is dirty
selected maximum release date for python packages: 9999-01-01 00:00:00
[22:54:28.216] Loading script /nix/store/iaz5jdp9ns3an3nid9c5pwi0kkm1w90f-filter-pypi-responses.py
[22:54:28.240] HTTP(S) proxy listening at *:46495.
[22:54:28.832][127.0.0.1:52574] client connect
[22:54:28.855][127.0.0.1:52574] server connect pypi.org:80 (151.101.0.223:80)
127.0.0.1:52574: GET http://pypi.org/
              << 301 Moved Permanently 0b
[22:54:28.860][127.0.0.1:52574] server disconnect pypi.org:80 (151.101.0.223:80)
[22:54:28.860][127.0.0.1:52574] client disconnect
Collecting pip==23.1
  Using cached pip-23.1-py3-none-any.whl (2.1 MB)
ERROR: Could not find a version that satisfies the requirement wheel==0.40.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0a0, 0.30.0, 0.31.0, 0.31.1, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.33.4, 0.33.5, 0.33.6, 0.34.0, 0.34.1, 0.34.2, 0.35.0, 0.35.1, 0.36.0, 0.36.1, 0.36.2, 0.37.0, 0.37.1, 0.38.0, 0.38.1, 0.38.2, 0.38.3, 0.38.4)
ERROR: No matching distribution found for wheel==0.40.0

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python -m pip install --upgrade pip
Traceback (most recent call last):
  File "/nix/store/8g5azrch03m8fy2x7xzz2ygrdpikxkpj-python3.10-fetch_pip_metadata/bin/.fetch_pip_metadata-wrapped", line 9, in <module>
    sys.exit(fetch_pip_metadata())
  File "/nix/store/8g5azrch03m8fy2x7xzz2ygrdpikxkpj-python3.10-fetch_pip_metadata/lib/python3.10/site-packages/fetch_pip_metadata/__init__.py", line 83, in fetch_pip_metadata
    venv_path = prepare_venv(
  File "/nix/store/8g5azrch03m8fy2x7xzz2ygrdpikxkpj-python3.10-fetch_pip_metadata/lib/python3.10/site-packages/fetch_pip_metadata/__init__.py", line 26, in prepare_venv
    subprocess.run(
  File "/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp.iNT9qNDTL2/tmp27gmz362/.venv/bin/pip', 'install', '--upgrade', 'pip==23.1', 'wheel==0.40.0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/nix/store/q53hia1skm09zcjwgx1bbdwsw6lq9505-refresh/bin/refresh", line 37, in <module>
    lock_data = run_refresh_scripts(refresh_scripts)
  File "/nix/store/q53hia1skm09zcjwgx1bbdwsw6lq9505-refresh/bin/refresh", line 33, in run_refresh_scripts
    refresh_scripts[name] = run_refresh_script(value["script"])
  File "/nix/store/q53hia1skm09zcjwgx1bbdwsw6lq9505-refresh/bin/refresh", line 19, in run_refresh_script
    subprocess.run(
  File "/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/4mb2285lpaf598xwzgjkwz3hcjj38qmv-script.sh']' returned non-zero exit status 1.

```
From what I can gather out of here, even if I set the pip version to 23.2.1 and remove the snapshot date, it still is using pip version 23.0.1.

**Comment by DavHau** [comment]
This is a problem with your local pip cache and can be fixed like this:
```command
rm -rf $HOME/.cache/pip/
```

**Comment by purepani** [comment]
Thanks!
Is there a plan to put this type of cache in the nix store in the future, as these types of local machine issues(i.e. messing up the pip cache) are the type of thing I hope to avoid by using nix?

**Comment by DavHau** [comment]
We could just run the whole locking script in a sandbox to prevent such side effects, but that way you'd have to re-download all wheels each time you re-lock which can be slightly annoying if you have many packages or a slow internet connection.
It's a tradeoff between purity and performance here.

It definitely seems like a bug in pip BTW, maybe we just have to update the pip version.

**Comment by purepani** [comment]
It might be good to at least optionally run it in a sandbox. At least, if
I'm not running nix without an - - impure flag, I don't expect artifacts in
the system to exist that affect the install.

**Comment by purepani** [comment]
In fact that's probably the reason I wasn't able to successfully debug this
on my own.
I assumed that if I reset everything(deleted GC roots so that everything
was garbage collected), it should work, if I just reinstall it. Once that
didn't happen I had no recourse for debugging.

**Comment by DavHau** [comment]
Ok, I understand the confusion. But it's also worth mentioning that `nix run` always runs an executable inside the current environment. Never in the sandbox.
