### ISSUE TITLE
nodejs: native module compilation failure, need help configuring nativeBuildInputs

### ISSUE THREAD

**Issue by eflanagan0** [nix-community/dream2nix#900]
I am exploring whether dream2nix is a good fit for packaging a proprietary node.js application that uses [node-canvas](https://github.com/Automattic/node-canvas/).
I have enjoyed chasing successful building since `canvas` module requires native compilation and it lacks an upstream `package-lock.json`.

## issue reproduction
- clone / copy assets from https://git.sr.ht/~efx/nix-flakes-examples/commit/664b405974a2c253eddf83ef04576bb952c59585
- on a x86_64 Linux system, run `nix build ./#default`

From what I can tell, the build fails because `pkg-config` is not found.

<details>
<summary>nix log of failed derivation</summary>

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/yrr8a6rnx12jshc25cr2l2z6q7cd189m-canvas-2.11.2.tgz-extracted
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhaseNodejs" }
Running phase: patchPhaseNodejs
package.json: Pinning version '1.0.11' to '1.0.11' for dependency '@mapbox/node-pre-gyp'
package.json: Pinning version '2.19.0' to '2.19.0' for dependency 'nan'
package.json: Pinning version '3.1.1' to '3.1.1' for dependency 'simple-get'
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
installing: @mapbox/node-pre-gyp
installing: @mapbox/.bin
installing: nan
installing: simple-get
symlinking executable. dest: ../canvas/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp; source: /build/package/.bin/node-pre-gyp
Symlinking transitive executables to /build/package/.bin
won't overwrite existing symlink /build/package/.bin/node-pre-gyp. current target: ../canvas/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp
@nix { "action": "setPhase", "phase": "buildPhaseNodejs" }
Running phase: buildPhaseNodejs
executing buildPhaseNodejs
[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mconfig[0m production Use `--omit=dev` instead.
[0m
> canvas@2.11.2 install
> node-pre-gyp install --fallback-to-build --update-binary

[37;40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35mit worked if it ends with[0m ok
[0m[37;40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35musing[0m node-pre-gyp@1.0.11
[0m[37;40mnode-pre-gyp[0m [0m[32minfo[0m [0m[35musing[0m node@20.11.1 | linux | x64
[0m[37;40mnode-pre-gyp[0m [0m[32;40mhttp[0m [0m[35mGET[0m https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-x64.tar.gz
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35minstall request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com[0m 
[0m[37;40mnode-pre-gyp[0m [0m[30;43mWARN[0m [0m[35mPre-built binaries not installable for canvas@2.11.2 and node@20.11.1 (node-v115 ABI, glibc) (falling back to source compile with node-gyp)[0m 
[0m[37;40mnode-pre-gyp[0m [0m[30;43mWARN[0m [0m[35mHit error request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com[0m 
[0m[37;40mgyp[0m [32minfo[0m [35mit worked if it ends with[0m ok
[37;40mgyp[0m [32minfo[0m [35musing[0m node-gyp@10.0.1
[37;40mgyp[0m [32minfo[0m [35musing[0m node@20.11.1 | linux | x64
[37;40mgyp[0m [32minfo[0m [35mok[0m 
[37;40mgyp[0m [32minfo[0m [35mit worked if it ends with[0m ok
[37;40mgyp[0m [32minfo[0m [35musing[0m node-gyp@10.0.1
[37;40mgyp[0m [32minfo[0m [35musing[0m node@20.11.1 | linux | x64
[37;40mgyp[0m [32minfo[0m [35mfind Python[0m using Python version 3.11.8 found at "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/bin/python3"
[37;40mgyp[0m [30;43mWARN[0m [35mread config.gypi[0m ENOENT: no such file or directory, open '/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources/include/node/config.gypi'
[37;40mgyp[0m [32minfo[0m [35mspawn[0m /nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/bin/python3
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m [
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m 'binding.gyp',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-f',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m 'make',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-I',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '/build/package/canvas/build/config.gypi',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-I',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-I',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources/common.gypi',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dlibrary=shared_library',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dvisibility=default',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dnode_root_dir=/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dnode_gyp_dir=/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dnode_lib_file=/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources/$(Configuration)/node.lib',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dmodule_root_dir=/build/package/canvas',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Dnode_engine=v8',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '--depth=.',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '--no-parallel',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '--generator-output',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m 'build',
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m '-Goutput_dir=.'
[37;40mgyp[0m [32minfo[0m [35mspawn args[0m ]
/nix/store/4vzal97iq3dmrgycj8r0gflrh51p8w1s-bash-5.2p26/bin/sh: line 1: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
[37;40mgyp[0m [31;40mERR![0m [35mconfigure error[0m 
[37;40mgyp[0m [31;40mERR![0m [35mstack[0m Error: `gyp` failed with exit code: 1
[37;40mgyp[0m [31;40mERR![0m [35mstack[0m at ChildProcess.<anonymous> (/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
[37;40mgyp[0m [31;40mERR![0m [35mstack[0m at ChildProcess.emit (node:events:518:28)
[37;40mgyp[0m [31;40mERR![0m [35mstack[0m at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[37;40mgyp[0m [31;40mERR![0m [35mSystem[0m Linux 6.1.81
[37;40mgyp[0m [31;40mERR![0m [35mcommand[0m "/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/bin/node" "/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/build/package/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/build/package/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115" "--nodedir=/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources"
[37;40mgyp[0m [31;40mERR![0m [35mcwd[0m /build/package/canvas
[37;40mgyp[0m [31;40mERR![0m [35mnode -v[0m v20.11.1
[37;40mgyp[0m [31;40mERR![0m [35mnode-gyp -v[0m v10.0.1
[37;40mgyp[0m [31;40mERR![0m [35mnot ok[0m 
[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m 
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: Failed to execute '/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/bin/node /nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/build/package/canvas/build/Release/canvas.node --module_name=canvas --module_path=/build/package/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115 --nodedir=/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources' (1)
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.<anonymous> (/nix/store/2xqcc1ph4v4id0mg8dg4h3df6zyfr5cf-__at__mapbox__slash__node-pre-gyp-1.0.11/lib/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (node:events:518:28)
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at maybeClose (node:internal/child_process:1105:16)
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Linux 6.1.81
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/bin/node" "/build/package/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m /build/package/canvas
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v20.11.1
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mnode-pre-gyp -v[0m v1.0.11
[0m[37;40mnode-pre-gyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m 
[0mFailed to execute '/nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/bin/node /nix/store/rxpjn1vzbpv0a2i5lx887wka8054gpwj-nodejs-20.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/build/package/canvas/build/Release/canvas.node --module_name=canvas --module_path=/build/package/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115 --nodedir=/nix/store/b8mly6y6crc93vqlip3kb6b4y83465sp-node-sources' (1)

```

</details>

I expect it to succeed because I provide `pkg-config` to `mkDerivation`.

## question, misc
Do you know how I can configure `default.nix` to find `pkg-config`? 

As an aside, I was able to package the `canvas` module within a flake [here](https://git.sr.ht/~efx/nix-flakes-examples/tree/main/item/npm-canvas/flake.nix).

**Comment by hsjobeki** [comment]
Could you provide a link to your repository or code example how you configured the dream2nix node module?
